# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: Topics
    url: tags/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40
  - name: MDCS
    url: MDCS/
    weight: 50
